---
labels: ["docs"]
discussion:
  category: Announcements
  title: "[Announcement] {{ title }}"
  body: |
    ## Summary
    {{ summary }}

    ## Details
    {{ details }}

    ## Links
    - Related Issues/PRs: {{ links }}