openapi: 3.0.3
info:
  title: LPR Server API
  version: 1.0.0
  description: |
    Read-only endpoints for records and cameras. Primary write path is WebSocket; MQTT as fallback.
servers:
  - url: http://localhost:8765
paths:
  /api/records:
    get:
      summary: List LPR records
      parameters:
        - in: query
          name: limit
          schema: { type: integer, default: 20, minimum: 1, maximum: 100 }
        - in: query
          name: camera_id
          schema: { type: string }
        - in: query
          name: plate_number
          schema: { type: string }
      responses:
        '200':
          description: Records
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /api/cameras:
    get:
      summary: List cameras
      responses:
        '200':
          description: Cameras
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
components:
  schemas:
    DetectionMessage:
      $ref: ../schemas/json/detection.schema.json
    HealthMessage:
      $ref: ../schemas/json/health.schema.json
    ConfigMessage:
      $ref: ../schemas/json/config.schema.json