name: Edge CI

on:
  pull_request:
    branches: [ monorepo/initial ]
    paths:
      - 'edge/**'
      - '!edge/**.md'
  push:
    branches: [ monorepo/initial ]
    paths:
      - 'edge/**'
      - '!edge/**.md'

jobs:
  edge-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Static import check (best-effort)
        run: |
          # Avoid installing edge requirements (hardware deps). Just syntax check sources.
          python -m compileall -q edge/v1_3/src || true